config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  # as :user do
  #   patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
  #   get 'signin' => 'devise/sessions#new', as: :new_user_session
  #   post 'signin' => 'devise/sessions#create', as: :user_session
  #   get 'signup' => 'registrations#new', as: :new_user_registration
  #   post 'signup' => 'registrations#create', as: :user_registration
  #   delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  resource :user, only: [:edit, :update] do
    resource :avatar, only: [:destroy]
  end

  resource 'user-recent-transaction', 
    only: [:new, :create], 
    controller: :user_recent_transactions, 
    as: :user_recent_transaction
  resource 'user-next-transfers', 
    only: [:new, :show, :create],
    controller: :user_next_transfers,
    as: :user_next_transfers
  
  resources :service_providers, only: [:show], path: 'providers'

  resources :feedbacks, only: [:create]
  resources :referrals, only: [:create]

  resources :pages, only: [:show]

  root to: 'user_next_transfers#new'

  get 'how-to', to: 'pages#show', defaults: {id: 'how_to'}
  get 'privacy', to: 'pages#show', defaults: {id: 'privacy'}
  get 'terms', to: 'pages#show', defaults: {id: 'terms'}
  
  get 'welcome' => 'welcome#index'
  get 'blog' => redirect('http://www.saveonsend.com/blog')
  get '*path' => 'welcome#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                            :integer          not null, primary key
#  email                         :string(255)      default(""), not null
#  encrypted_password            :string(255)      default(""), not null
#  reset_password_token          :string(255)
#  reset_password_sent_at        :datetime
#  remember_created_at           :datetime
#  sign_in_count                 :integer          default(0), not null
#  current_sign_in_at            :datetime
#  last_sign_in_at               :datetime
#  current_sign_in_ip            :inet
#  last_sign_in_ip               :inet
#  confirmation_token            :string(255)
#  confirmed_at                  :datetime
#  confirmation_sent_at          :datetime
#  unconfirmed_email             :string(255)
#  failed_attempts               :integer          default(0), not null
#  unlock_token                  :string(255)
#  locked_at                     :datetime
#  first_name                    :string(255)
#  last_name                     :string(255)
#  zipcode                       :string(255)
#  money_transfer_destination_id :integer
#  created_at                    :datetime
#  updated_at                    :datetime
#  provider                      :string(255)
#  uid                           :string(255)
#  phone                         :string(255)
#  accept_terms                  :boolean
#  accept_emails                 :boolean
#  level_id                      :integer
#  points                        :integer          default(0)
#  about_me                      :string(1024)
#  avatar                        :string(255)
#

class User < ActiveRecord::Base
  US_PHONE_REGEX = /\A(?:\([2-9]\d{2}\)\ ?|[2-9]\d{2}(?:\-?|\ ?))[2-9]\d{2}[- ]?\d{4}\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable,
         :omniauthable, omniauth_providers: [:facebook],
         authentication_keys: [:login]

  belongs_to :money_transfer_destination, class_name: Country

  has_many :recent_transactions, class: User::RecentTransaction
  has_many :next_transfers, class: User::NextTransfer

  has_many :feedbacks

  has_many :referrals

  belongs_to :level, class_name: User::Level

  #mount_uploader :avatar, AvatarUploader  

  # validations
  #validates_presence_of :first_name
  #validates_presence_of :zipcode, unless: :skip_additional_info?
  validates_presence_of :money_transfer_destination, unless: :skip_additional_info?
  validates_length_of :about_me, maximum: 1024

  validates :phone, uniqueness: {case_sensitive: false}, format: {with: US_PHONE_REGEX}, 
    presence: true, if: :email_blank?

  validates_acceptance_of :accept_terms, allow_nil: false, 
    accept: true, on: :create

  before_validation :fill_phone, on: :create

  validates_presence_of :first_name, :zipcode, on: :update
  validates_format_of :zipcode, with: /\A[0-9]{5}(?:-[0-9]{4})?\Z/, on: :update
  validate :validity_of_confirmation_code, on: :update, if: :email_blank?

  attr_accessor :confirmation_code

  # login by email or phone : begin
  def login=(login)
    @login = login
  end

  def login
    @login || self.email || self.phone
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(phone) = :value OR lower(email) = :value", {value: login}]).first
    else
      where(conditions.to_h).first
    end
  end
  # login by email or phone : end

  def password_required?
    # Password is required if it is being set, but not for new records
    if !persisted? 
      false
    else
      !password.nil? || !password_confirmation.nil?
    end
  end

  def email_required?
    phone_blank?
  end

  def prefered_currency
    money_transfer_destination.try(:receive_currency)
  end

  def full_name
    [first_name, last_name].join(' ').strip
  end

  def skip_additional_info!
    @skip_additional_info = true
  end

  def skip_additional_info?
    @skip_additional_info
  end

  def complete?
    zipcode.present? && money_transfer_destination.present?
  end

  def phone_blank?
    phone.blank?
  end

  def email_blank?
    email.blank? && phone.present?
  end

  def phone_with_international_code
    if phone.present?
      "+1#{phone.gsub(/[^\d]/, '')}"
    end
  end

  # new function to set the password without knowing the current password used in our confirmation controller. 
  def attempt_set_password_and_required_parameters(params)
    confirmation_form_params = %i{password password_confirmation first_name last_name zipcode confirmation_code}
    p = {}
    confirmation_form_params.each {|attr_name| p[attr_name] = params[attr_name]}
    update_attributes(p)
  end
  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  def password_match?
    password == password_confirmation
  end

  # new function to provide access to protected method unless_confirmed
  def only_if_unconfirmed
    pending_any_confirmation {yield}    
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.skip_additional_info!
    end
  end

  def send_confirmation_instructions_by_sms
    # send confirmation instruction by phone

    begin
      Twilio::REST::Client.new.messages.create(
        from: Rails.application.secrets.twilio_phone_number,
        to: phone_with_international_code,
        body: I18n.t('sms.confirmation_code', code: self.confirmation_token)
      )
    rescue Twilio::REST::RequestError => e
      self.errors.add(:base, I18n.t('sms.sending_failed'))
      raise ActiveRecord::Rollback
    end

    self
  end

  def remove_avatar!
    result = false

    if avatar.present?
      Cloudinary::Uploader.destroy(avatar, invalidate: true)
      update_attribute(:avatar, nil)
    
      result = true
    end

    result
  end

  protected
  def generate_confirmation_token
    if email.present?
      super
    else
      token = rand(10000..99999)
      self.confirmation_token = token
      self.confirmation_sent_at = Time.now.utc
    end
  end

  def send_on_create_confirmation_instructions
    if email.present?
      send_confirmation_instructions
    elsif phone.present?
      send_confirmation_instructions_by_sms
    end
  end

  def send_confirmation_notification?
    confirmation_required? && !@skip_confirmation_notification && (self.email.present? || self.phone.present?)
  end

  private
  def fill_phone
    if email.match(US_PHONE_REGEX)
      self.phone = email
      self.email = ''
    end
  end

  def validity_of_confirmation_code
    errors.add :confirmation_code unless confirmation_token == confirmation_code
  end

  # Rails Admin Settings
  rails_admin do
    list do
      field :email do
        label 'Email'
      end
      field :phone
      field :first_name
      field :last_name
      field :zipcode
      field :money_transfer_destination
      field :created_at
    end

    show do
      field :email do
        label 'Email'
      end

      field :phone
      field :first_name
      field :last_name
      field :avatar
      field :zipcode
      field :money_transfer_destination
      field :level
      field :points
      field :about_me
      field :accept_terms
      field :accept_emails

      field :recent_transactions
      field :next_transfers
      field :feedbacks
      field :created_at
    end

    edit do
      field :email do
        label 'Email'
      end
      field :phone
      field :first_name
      field :last_name
      field :avatar
      field :zipcode
      field :money_transfer_destination
      field :level
      field :points
      field :about_me
      field :accept_terms
      field :accept_emails
      field :feedbacks
      
      field :password
      field :password_confirmation
    end
  end
end

app/models/user/input_error.rb
# == Schema Information
#
# Table name: user_input_errors
#
#  id       :integer          not null, primary key
#  user_id  :integer
#  location :string(255)
#  messages :string(2048)
#

class User::InputError < ActiveRecord::Base
  belongs_to :user
end

app/models/user/level.rb
# == Schema Information
#
# Table name: user_levels
#
#  id   :integer          not null, primary key
#  name :string(255)
#  slug :string(255)
#

class User::Level < ActiveRecord::Base
end

app/models/user/next_transfer.rb
# == Schema Information
#
# Table name: user_next_transfers
#
#  id                                  :integer          not null, primary key
#  user_id                             :integer
#  amount_send_cents                   :integer          default(0), not null
#  amount_receive_cents                :integer          default(0), not null
#  receive_currency                    :string(3)
#  originating_source_of_funds_id      :integer
#  destination_preference_for_funds_id :integer
#  created_at                          :datetime
#  updated_at                          :datetime
#  money_transfer_destination_id       :integer
#

class User::NextTransfer < ActiveRecord::Base
  belongs_to :user

  belongs_to :originating_source_of_funds, class_name: PaymentMethod
  belongs_to :destination_preference_for_funds, class_name: PaymentMethod

  belongs_to :money_transfer_destination, class_name: Country

  monetize :amount_send_cents
  monetize :amount_receive_cents, with_model_currency: :receive_currency
 
  # Use model level currency
  register_currency :usd

  # validation
  validates_presence_of :originating_source_of_funds, :destination_preference_for_funds
  validates_presence_of :receive_currency
  validates_presence_of :money_transfer_destination, unless: :user_present?
  
  validates_numericality_of :amount_send, greater_than: 0, unless: :amount_receive_present?
  validates_numericality_of :amount_receive, greater_than: 0, unless: :amount_send_present?

  def payment_methods_same_as(remittance_term)
    originating_source_of_funds == remittance_term.send_method &&
      destination_preference_for_funds == remittance_term.receive_method
  end

  private
  def amount_send_present?
    amount_send_cents >= 0
  end

  def amount_receive_present?
    amount_receive_cents > 0
  end

  def user_present?
    !!user
  end
end

app/controllers/user/avatars_controller.rb
class AvatarsController < ApplicationController
  before_filter :authenticate_user!
  
  def destroy
    respond_to do |format|
      format.json do
        render json: current_user.remove_avatar!
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user

    respond_to do |format|
      format.html do 
        @user.update_attributes(params.require(:user).permit(:first_name, :last_name, :zipcode, :about_me))
        
        if @user.valid?
          redirect_to(edit_user_path)
        else
          render(:edit)
        end
      end
      
      format.json do 
        if params[:avatar].present?
          preloaded = Cloudinary::PreloadedFile.new(params[:avatar])         
          raise "Invalid upload signature" if !preloaded.valid?
          
          Cloudinary::Uploader.destroy(@user.avatar, invalidate: true) if @user.avatar.present?

          @user.update_attribute(:avatar, preloaded.identifier)
        end

        render(json: @user.valid?)
      end
    end
  end
end

app/views/users/edit.html.slim
- set_meta_tags :title => t('.title'),
                :description => t('.description'),
                :og => { :title => t('.title'), :description => t('.description') }

section.content.user-page
  .container
    .row
      .user-page-title
        h3= t('.page_title')

    - unless @user.errors.empty?
      .row
        .col-xs-12.align-center.alert.alert-danger data-error='1'
          ul
            - @user.errors.full_messages.each do |err_msg|
              li= err_msg

    .row
      .user-page-wrap
        = form_for(@user, html: {class: 'form-horizontal', role: 'form'}) do |f|
          .col-xs-12.col-sm-4
            // avatar
            .form-group
              .upload_error.alert.alert-danger.hidden
                = t('.image_format_unsupported')
              - if @user.avatar?
                .user-page-avatar
                  .user-page-avatar-img
                    = cl_image_tag(@user.avatar, crop: :fill, width: 162, height: 162)
                  .progress
                    .progress-bar.progress-bar-info.progress-bar-striped role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"
                      span.sr-only= t('.complete')

                .user-page-avatar-btn
                  span.hidden.btn.btn-info.user-page-avatar-add
                    i.fa.fa-plus
                    span= t('.add')
                    = cl_image_upload_tag(:avatar)

                  a.btn.btn-info.user-page-avatar-change
                    i.fa.fa-refresh
                    span= t('.change')
                    = cl_image_upload_tag(:avatar)

                  = link_to user_avatar_path, method: :delete, remote: true, class: 'btn btn-danger user-page-avatar-remove' do
                    i.fa.fa-trash
                    span= t('.delete')

              - else
                .user-page-avatar
                  .user-page-avatar-img
                    = image_tag('default-image.png')
                  .progress
                    .progress-bar.progress-bar-info.progress-bar-striped role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"
                      span.sr-only= t('.complete')

                .user-page-avatar-btn
                  span.btn.btn-info.user-page-avatar-add
                    i.fa.fa-plus
                    span= t('.add')
                    = cl_image_upload_tag(:avatar)

                  a.hidden.btn.btn-info.user-page-avatar-change
                    i.fa.fa-refresh
                    span= t('.change')
                    = cl_image_upload_tag(:avatar)

                  = link_to user_avatar_path, method: :delete, remote: true, class: 'hidden btn btn-danger user-page-avatar-remove' do
                    i.fa.fa-trash
                    span= t('.delete')

          .col-xs-12.col-sm-8
            // status & point
            .form-group
              = f.label t('.status'), class: 'col-sm-4 control-label'
              .col-sm-8.col-lg-6
                - if @user.level.present?
                  .user-page-status class='#{@user.level.slug}-status'
                    = @user.level.name
        
                - if @user.points > 0
                  .user-page-points
                    = "#{@user.points} #{t('.points')}"

            // first name
            .form-group
              = f.label :first_name, class: 'col-sm-4 control-label'
              .col-sm-8.col-lg-6
                = f.text_field :first_name, class: 'form-control'
  
            // last name
            .form-group
              = f.label :last_name, class: 'col-sm-4 control-label'
              .col-sm-8.col-lg-6
                = f.text_field :last_name, class: 'form-control'
  
            // zipcode
            .form-group
              = f.label :zipcode, class: 'col-sm-4 control-label'
              .col-sm-8.col-lg-6
                = f.text_field :zipcode, class: 'form-control mask-zipcode'

          .col-xs-12  
            // about_me
            .form-group
              .user-page-about
                = f.label :about_me, class: 'col-xs-12 control-label'
                .col-xs-12
                  = f.text_area :about_me, rows: '4', cols: '1', class: 'form-control', placeholder: t('.about_me'), maxlength: '1024'
  
            .form-group
              .col-sm-7.col-sm-offset-5
                = button_tag type:"submit", class: "btn btn-primary btn-lg" do
                  i.fa.fa-fw.fa-check-circle-o
                  = t('.submit')