config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  # as :user do
  #   patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
  #   get 'signin' => 'devise/sessions#new', as: :new_user_session
  #   post 'signin' => 'devise/sessions#create', as: :user_session
  #   get 'signup' => 'registrations#new', as: :new_user_registration
  #   post 'signup' => 'registrations#create', as: :user_registration
  #   delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  resource :user, only: [:edit, :update] do
    resource :avatar, only: [:destroy]
  end

  resource 'user-recent-transaction', 
    only: [:new, :create], 
    controller: :user_recent_transactions, 
    as: :user_recent_transaction
  resource 'user-next-transfers', 
    only: [:new, :show, :create],
    controller: :user_next_transfers,
    as: :user_next_transfers
  
  resources :service_providers, only: [:show], path: 'providers'

  resources :feedbacks, only: [:create]
  resources :referrals, only: [:create]

  resources :pages, only: [:show]

  root to: 'user_next_transfers#new'

  get 'how-to', to: 'pages#show', defaults: {id: 'how_to'}
  get 'privacy', to: 'pages#show', defaults: {id: 'privacy'}
  get 'terms', to: 'pages#show', defaults: {id: 'terms'}
  
  get 'welcome' => 'welcome#index'
  get 'blog' => redirect('http://www.saveonsend.com/blog')
  get '*path' => 'welcome#index'
end

app/views/shared/_footer.html.slim
footer
  .container-fluid
    .row.feedback
      .col-xs-12
        = t('.feedback_cta').html_safe
        
    .row.follow-buttons
      .col-xs-12
        a.follow-button-facebook title='Follow on Facebook' href='//www.facebook.com/saveonsend' target='_blank' rel='nofollow'
          i.fa.fa-facebook
          span.follow-button-label Facebook

        a.follow-button-twitter title='Follow on Twitter' href='//twitter.com/intent/follow?source=followbutton&amp;variant=1.0&amp;screen_name=SaveOnSend' target='_blank' rel='nofollow'
          i.fa.fa-twitter
          span.follow-button-label Twitter
          
        a.follow-button-linkedin title='Follow on LinkedIn' href='//www.linkedin.com/company/saveonsend' target='_blank' rel='nofollow'
          i.fa.fa-linkedin
          span.follow-button-label LinkedIn
          
        a.follow-button-google title='Follow on Google' href='//plus.google.com/+Saveonsend' target='_blank' rel='publisher'
          i.fa.fa-google-plus
          span.follow-button-label Google
          
        a.follow-button-tumblr title='Follow on Tumblr' href='http://saveonsend.tumblr.com' target='_blank' rel='nofollow'
          i.fa.fa-tumblr
          span.follow-button-label Tumblr

    .row.footer
      .col-xs-12
        p
          | &copy;2015 SaveOnSend Inc.&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
          = link_to t('.terms'), terms_path
          | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
          = link_to t('.privacy'), privacy_path
          | &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
          = link_to t('.how_to'), how_to_path
          
    .row.disclosure
      .col-xs-12.col-sm-10.col-sm-offset-1
        p= t('.disclosure')

app/views/shared/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59380432-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/shared/_header.html.slim
header#header
  .navbar.navbar-default
    .container
      .navbar-header
        button.navbar-toggle.collapsed data-toggle="offcanvas" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar

        = link_to root_path, class: 'navbar-brand' do
          = image_tag "logo.png", { alt: t('.site'), title: t('.site'), class: 'img-responsive', width: '272' }

      #navbar.collapse.navbar-collapse
        ul.nav.nav-pills.navbar-right
          = render 'shared/sidebar'

app/views/shared/_notification.html.slim
.row.notification
  .container
    .row
      .col-xs-12.text-left
        p
          | #{t('.notice_test_version')} #{mail_to 'admin@saveonsend.com'}

app/views/shared/_select_country_ctrl.html.slim
- if current_user.nil? && cookies[:money_transfer_destination_id].nil?
  // money_transfer_destination
  .form-group
    = f.label :money_transfer_destination_id, class: [label_class, 'control-label valabel']
    div *{class: control_class}
      .country
        = f.collection_radio_buttons(:money_transfer_destination_id, Country.all.collect {|country| [ country.id, country.name ] }, :first, :last, {prompt: true, checked: resource.money_transfer_destination.try(:id)}) do |b|
          = b.label( class: "radio-inline", title: b.text )
            = b.radio_button
            = image_tag 'flags/' + b.text + '.png'

app/views/shared/_share.html.slim
.share
  ul.rrssb-buttons
    li.rrssb-facebook
      a.popup href='http://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583' rel='nofollow'
        i.fa.fa-facebook
  
    li.rrssb-twitter
      a.popup href='http://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583&via=saveonsend' rel='nofollow'
        i.fa.fa-twitter

    li.rrssb-googleplus
      a.popup href='http://api.addthis.com/oexchange/0.8/forward/googleplus/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583' rel='nofollow'
        i.fa.fa-google-plus
       
    li.rrssb-tumblr
      a.popup href='http://api.addthis.com/oexchange/0.8/forward/tumblr/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583' rel='nofollow'
        i.fa.fa-tumblr

    li.rrssb-linkedin
      a.popup href='http://api.addthis.com/oexchange/0.8/forward/linkedin/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583' rel='nofollow'
        i.fa.fa-linkedin
        
    li.rrssb-others
      a.popup href='http://api.addthis.com/oexchange/0.8/offer?url=#{request.base_url}#{request.script_name}#{request.path_info}&pubid=ra-552e8c035645c583' rel='nofollow'
        i.fa.fa-plus

app/views/shared/_sidebar.html.slim
- if current_user
  li= link_to_with_active t('.hi') + current_user.first_name, edit_user_path
  li= link_to_with_active t('.next_transfer'), new_user_next_transfers_path(anchor: 'new_user_next_transfer')
  li= link_to_with_active t('.recent_transaction'), new_user_recent_transaction_path
  li= link_to t('.blog'), 'http://www.saveonsend.com/blog/'
  li= link_to t('.sign_out'), destroy_user_session_path, method: :delete

- else
  - if current_page?(new_user_next_transfers_path)
    li= link_to t('.sign_up'), new_user_registration_path
  - else
    li.promo= link_to_with_active t('.sign_up'), new_user_registration_path
  li= link_to_with_active t('.next_transfer'), new_user_next_transfers_path(anchor: 'new_user_next_transfer')
  li= link_to_with_active t('.recent_transaction'), new_user_recent_transaction_path
  li= link_to t('.blog'), 'http://www.saveonsend.com/blog/'
  li= link_to_with_active t('.sign_in'), new_user_session_path