config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  # as :user do
  #   patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
  #   get 'signin' => 'devise/sessions#new', as: :new_user_session
  #   post 'signin' => 'devise/sessions#create', as: :user_session
  #   get 'signup' => 'registrations#new', as: :new_user_registration
  #   post 'signup' => 'registrations#create', as: :user_registration
  #   delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  resource :user, only: [:edit, :update] do
    resource :avatar, only: [:destroy]
  end

  resource 'user-recent-transaction', 
    only: [:new, :create], 
    controller: :user_recent_transactions, 
    as: :user_recent_transaction
  resource 'user-next-transfers', 
    only: [:new, :show, :create],
    controller: :user_next_transfers,
    as: :user_next_transfers
  
  resources :service_providers, only: [:show], path: 'providers'

  resources :feedbacks, only: [:create]
  resources :referrals, only: [:create]

  resources :pages, only: [:show]

  root to: 'user_next_transfers#new'

  get 'how-to', to: 'pages#show', defaults: {id: 'how_to'}
  get 'privacy', to: 'pages#show', defaults: {id: 'privacy'}
  get 'terms', to: 'pages#show', defaults: {id: 'terms'}
  
  get 'welcome' => 'welcome#index'
  get 'blog' => redirect('http://www.saveonsend.com/blog')
  get '*path' => 'welcome#index'
end

app/models/remittance_term.rb
# == Schema Information
#
# Table name: remittance_terms
#
#  id                       :integer          not null, primary key
#  receive_country_id       :integer
#  service_provider_id      :integer
#  send_method_id           :integer
#  receive_method_id        :integer
#  receive_currency         :string(3)
#  send_amount_range_from   :float
#  send_amount_range_to     :float
#  fees_for_sending_cents   :integer          default(0), not null
#  fees_for_sending_percent :float            default(0.0)
#  fx_markup                :float
#  duration                 :string(255)
#  documentation            :text
#  promotions               :string(255)
#  service_quality          :integer
#

class RemittanceTerm < ActiveRecord::Base
  belongs_to :receive_country, class_name: Country
  belongs_to :service_provider
  belongs_to :send_method, class_name: PaymentMethod
  belongs_to :receive_method, class_name: PaymentMethod

  monetize :fees_for_sending_cents

  # Use model level currency
  register_currency :usd

  attr_accessor :highlight

  def send_amount_with_fee(amount)
    amount_with_fee = amount + fees_for_sending
    amount_with_fee += (amount*fees_for_sending_percent)/100 if fees_for_sending_percent > 0
    amount_with_fee
  end

  def all_fees(amount)
    fees_for_sending_cents.fdiv(amount.cents)*100 + fees_for_sending_percent + fx_markup
  end

  def estimated_receive_amount(amount, currency)
    amount = amount.exchange_to(currency)
    amount - amount*fx_markup/100.0
  end

  def estimated_send_amount(amount, currency)
    amount = (amount + amount*fx_markup/100.0).exchange_to('USD')
    Money.new(amount + fees_for_sending + amount*fees_for_sending_percent/100.0)
  end

  def transaction_cost(amount, currency)
    cost = 0

    if expense > 0
      cost = Money.new(amount*expense/100, 'USD')
      cost = cost.exchange_to(receive_currency) if currency != 'USD'
    end

    cost
  end

  def highlighted?
    !!highlight
  end

  def self.least_expensive(amount_send: nil, amount_receive: nil, receive_country: nil, receive_currency: nil, send_method: nil, receive_method: nil)
    return if (amount_send == 0 && amount_receive == 0) || receive_country.nil? || receive_currency.nil?

    amount =  if amount_send > 0 
                amount_send 
              else
                amount_receive.exchange_to('USD')
              end

    order_by = ['expense']

    # same as all_fees
    select_query = %Q{*, (fees_for_sending_cents::FLOAT/#{amount.cents}*100 + 
                          fees_for_sending_percent + fx_markup) as expense}

    if send_method && receive_method
      select_query += %Q{
        , (send_method_id = #{send_method.id} AND receive_method_id = #{receive_method.id}) 
        as same_methods 
      }

      order_by += ['same_methods DESC']
    end

    least_expensive_services = RemittanceTerm.where(receive_country: receive_country, 
                         receive_currency: receive_currency)
                  .where("#{amount.to_f} >= send_amount_range_from AND " +
                         "#{amount.to_f} <= send_amount_range_to")
                  .select(select_query)
                  .order(order_by)

    if send_method && receive_method
      filtered_least_expensive_services = least_expensive_services.to_a 
     
      if filtered_least_expensive_services.first.present? &&
          (filtered_least_expensive_services.first.send_method != send_method ||
          filtered_least_expensive_services.first.receive_method != receive_method)

        lowest_expese = filtered_least_expensive_services.first.expense
        filtered_least_expensive_services.each do |service|
          service.highlight = true if lowest_expese == service.expense
        end
      end

      filtered_least_expensive_services.to_a.keep_if do |item| 
        (item.highlighted?) ||
        (item.send_method == send_method && item.receive_method == receive_method)
      end
    else
      least_expensive_services
    end
  end

  def self.save_on_transaction(transaction)
    saving = 0

    amount_send = transaction.amount_sent
    receive_currency = transaction.currency
    receive_country = transaction.money_transfer_destination || transaction.user.money_transfer_destination 

    least_expensive_service = least_expensive(amount_send: amount_send, 
                                      receive_country: receive_country, 
                                      receive_currency: receive_currency).first
   
    if least_expensive_service
      fx_markup = least_expensive_service.fx_markup
      saving = transaction.total_cost(fx_markup) -
        least_expensive_service.transaction_cost(amount_send, receive_currency)
    end

    saving > 0 ? saving : 0
  end
  
  def self.import_from_csv(csv_path = nil)
    csv_file = csv_path.nil? ? Rails.root.join('db/seeds', 'remittance_terms.csv') : open(csv_path)

    remittance_terms = CSV.read(csv_file, headers: :first_row)

    remittance_terms.each do |data|
      # Receive country
      receive_country = Country.find_by(name: data['Receive country'])
      next if receive_country.nil?

      # Remit name
      service_provider = ServiceProvider.find_by('lower(name) = ?', data['Remit name'].downcase)
      next if service_provider.nil?

      # Send method
      send_method = PaymentMethod.find_by(slug: data['Sending type'])
      next if send_method.nil?

      # Receive method
      receive_methods = data['Receiving type'].split(',')
      receive_methods.map!{|receive_method_slug| PaymentMethod.find_by(slug: receive_method_slug.strip)}.delete_if(&:nil?)
      next if receive_methods.empty?

      receive_methods.each do |receive_method|
        remittance_term_attrs = {
          receive_country: receive_country, 
          service_provider: service_provider,
          send_method: send_method,
          receive_method: receive_method,
          receive_currency: data['To which currency?'],
          send_amount_range_from: data['Send amount range ($USD) - From'].gsub(',', '_'),
          send_amount_range_to: data['Send amount range ($USD) - To'].gsub(',', '_'),
          fees_for_sending: data['Fees for sending - USD'] || 0,
          fees_for_sending_percent: data['Fees for sending - %'] || 0,
          fx_markup: data['FX markup'] || 0,
          duration: data['Send-to-receive - Duration (hours)'],
          documentation: data['Documentation requirements'],
          promotions: data['Promotions'],
          service_quality: data['Service quality']
        }

        RemittanceTerm.create(remittance_term_attrs)
      end
    end
  end
end

app/views/remittance_terms/_remittance_term.html.slim
- if remittance_term.highlighted?
  - rowspan = '2'
- else
  - rowspan = '1'

tr *{class: remittance_term.highlighted? ? 'option-best' : ''}
  - if remittance_term.highlighted?
    td.option-method-label

  - else
    td
      = link_to(image_tag('provider-icons/' + remittance_term.service_provider.slug + '.png', width: '100', height: '48'), service_provider_path(remittance_term.service_provider), title: remittance_term.service_provider.name)

  - if @from_to_show
    - if remittance_term.highlighted?
      td.option-method-label
        .option-method-wrap
          span= t('.best_method')

    - else
      td
        i.fa *{class: "fa-#{remittance_term.send_method.name.parameterize.downcase}"} &nbsp;
        | &mdash;&nbsp;
        i.fa *{class: "fa-#{remittance_term.receive_method.name.parameterize.downcase}"}

  td rowspan=rowspan
    - if @user_next_transfer.amount_send > 0
      - total_amount = remittance_term.send_amount_with_fee(@user_next_transfer.amount_send)
      = humanized_money_with_symbol(total_amount.to_f.round)

    - else
      - total_amount = remittance_term.estimated_send_amount(@user_next_transfer.amount_receive, @user_next_transfer.receive_currency)
      = humanized_money_with_symbol(total_amount.to_f.round)

  td.option-margin rowspan=rowspan
    - if @user_next_transfer.amount_send > 0
      = number_to_percentage(remittance_term.all_fees(@user_next_transfer.amount_send), precision: 1)

    - else
      = number_to_percentage(remittance_term.all_fees(@user_next_transfer.amount_receive.exchange_to('USD')), precision: 1)

  td rowspan=rowspan
    - if @user_next_transfer.amount_send > 0
      | #{@user_next_transfer.receive_currency}&nbsp;
        #{money_without_cents(remittance_term.estimated_receive_amount(@user_next_transfer.amount_send, @user_next_transfer.receive_currency))}

    - else
      | #{@user_next_transfer.receive_currency}&nbsp;
        #{money_without_cents(@user_next_transfer.amount_receive)}

  td rowspan=rowspan
    = remittance_term.duration

  td rowspan=rowspan
    =link_to(service_provider_path(remittance_term.service_provider)) do
      .user-rating= display_average_rating_for_remittance_term(remittance_term)
      
- if @from_to_show
  - if remittance_term.highlighted?
    tr *{class: remittance_term.highlighted? ? 'option-best' : ''}
        td
          = link_to(image_tag('provider-icons/' + remittance_term.service_provider.slug + '.png', width: '100', height: '48'), service_provider_path(remittance_term.service_provider), title: remittance_term.service_provider.name)

        td.option-method-ico
            div
              =link_to '#apply_payment_methods' do
                i.fa *{class: "fa-#{remittance_term.send_method.name.parameterize.downcase}"} &nbsp;
                | &mdash;&nbsp;
                i.fa *{class: "fa-#{remittance_term.receive_method.name.parameterize.downcase}"}
              .hidden.send_method_id= remittance_term.send_method.id
              .hidden.receive_method_id= remittance_term.receive_method.id