config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    omniauth_callbacks: 'omniauth_callbacks'
  }

  # as :user do
  #   patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
  #   get 'signin' => 'devise/sessions#new', as: :new_user_session
  #   post 'signin' => 'devise/sessions#create', as: :user_session
  #   get 'signup' => 'registrations#new', as: :new_user_registration
  #   post 'signup' => 'registrations#create', as: :user_registration
  #   delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  # end
  
  resource :user, only: [:edit, :update] do
    resource :avatar, only: [:destroy]
  end

  resource 'user-recent-transaction', 
    only: [:new, :create], 
    controller: :user_recent_transactions, 
    as: :user_recent_transaction
  resource 'user-next-transfers', 
    only: [:new, :show, :create],
    controller: :user_next_transfers,
    as: :user_next_transfers
  
  resources :service_providers, only: [:show], path: 'providers'

  resources :feedbacks, only: [:create]
  resources :referrals, only: [:create]

  resources :pages, only: [:show]

  root to: 'user_next_transfers#new'

  get 'how-to', to: 'pages#show', defaults: {id: 'how_to'}
  get 'privacy', to: 'pages#show', defaults: {id: 'privacy'}
  get 'terms', to: 'pages#show', defaults: {id: 'terms'}
  
  get 'welcome' => 'welcome#index'
  get 'blog' => redirect('http://www.saveonsend.com/blog')
  get '*path' => 'welcome#index'
end

app/controllers/user_recent_transactions_controller.rb
class UserRecentTransactionsController < ApplicationController
  #before_filter :authenticate_user!
  before_filter :set_prefered_currency, only: [:new]

  include ActionView::Helpers::NumberHelper

  def new
    @user_recent_transaction = User::RecentTransaction.new(params[:user_recent_transaction])
  
    set_service_providers
  end

  def create
    #params[:user_recent_transaction][:documentation_requirements] = params[:user_recent_transaction][:documentation_requirements].join(',')

    # remove decimal part from amount send and receive
    params[:user_recent_transaction][:amount_sent] = params[:user_recent_transaction][:amount_sent].gsub(',', '_').to_i
    params[:user_recent_transaction][:amount_received] = params[:user_recent_transaction][:amount_received].gsub(',', '_').to_i

    if params[:user_recent_transaction][:money_transfer_destination_id]
      cookies[:money_transfer_destination_id] = params[:user_recent_transaction][:money_transfer_destination_id]

      selected_country = Country.find(params[:user_recent_transaction][:money_transfer_destination_id])
      params[:user_recent_transaction][:currency] = selected_country.receive_currency.first if selected_country.receive_currency.size == 1
    end

    if current_user.nil? && cookies[:money_transfer_destination_id]
      params[:user_recent_transaction][:money_transfer_destination_id] = cookies[:money_transfer_destination_id]
    end

    # convert date from string
    begin
      params[:user_recent_transaction][:date] = Date.strptime(params[:user_recent_transaction][:date], '%m/%d/%Y') if params[:user_recent_transaction][:date]
    rescue
    end

    recent_transaction_attrs = params.require(:user_recent_transaction)
      .permit(:date, :currency, :amount_sent, :amount_received, :originating_source_of_funds_id,
              :service_provider_id, :destination_preference_for_funds_id, :fees_for_sending,
              :fees_for_receiving, :send_to_receive_duration, :send_to_receive_duration_interval,
              :documentation_requirements, :promotion,
              :money_transfer_destination_id,
              service_provider_attributes: [:name, :money_transfer_page], 
              feedback_attributes: [:service_quality, :comments]
             )

    if recent_transaction_attrs[:service_provider_id].present? && recent_transaction_attrs[:service_provider_attributes].present?
      recent_transaction_attrs.delete(:service_provider_attributes)
    end

    if recent_transaction_attrs[:service_provider_attributes].present?
      recent_transaction_attrs[:service_provider_attributes][:created_by] = current_user
    end

    if recent_transaction_attrs[:feedback_attributes].present? && current_user.present?
      recent_transaction_attrs[:feedback_attributes][:user] = current_user
    end

    if current_user.present?
      @user_recent_transaction = current_user.recent_transactions.create(recent_transaction_attrs)
    else
      @user_recent_transaction = User::RecentTransaction.create(recent_transaction_attrs) 
    end

    if @user_recent_transaction.persisted?
      notice = I18n.t('notice.best_rate')

      more_money = RemittanceTerm.save_on_transaction(@user_recent_transaction)

      if more_money > 0
        destination_country = if current_user.present?
                                current_user.money_transfer_destination.name
                              else
                                @user_recent_transaction.money_transfer_destination.name
                              end

        notice = I18n.t('notice.save_on_transaction',
                        destination_country: destination_country,
                        saving: number_with_delimiter(more_money.to_i),
                        currency: more_money.currency.iso_code)
      end

      redirect_to(new_user_next_transfers_path, notice: notice)
    else
      track_input_error(@user_recent_transaction)
      set_prefered_currency
      set_service_providers

      render :new
    end
  end

  protected
  def set_service_providers
    if current_user.present? || cookies[:money_transfer_destination_id].present?
      if current_user.present?
        @service_providers = ServiceProvider.for_country(current_user.money_transfer_destination)
      else
        money_transfer_destination = Country.find(cookies[:money_transfer_destination_id].to_i)
        @service_providers = ServiceProvider.for_country(money_transfer_destination)
      end
    end

    @service_providers ||= ServiceProvider.created_by_admin
  end
end

app/views/user_recent_transactions/new.html.slim
- set_meta_tags :title => t('.title'),
                :description => t('.description'),
                :og => { :title => t('.title'), :description => t('.description') }

section.content-header
  .container
    .row
      .col-xs-12
        h2= t('.benefits_title')
        .align-center.text-left
          ul
            - t('.benefits').each do |line, text|
              li 
                i.fa.fa-check 
                | #{text}

section.content.recent-tr-page
  .container
    .row
      .col-xs-12.intro.text-center
        h3= t('.see_how_much')
        p.align-center= t('.enter_info')
    
    // errors
    - if @user_recent_transaction.errors.full_messages.count > 0
      .row
        .col-xs-12.align-center.alert.alert-danger data-error='1'
          ul
            - @user_recent_transaction.errors.each do |attribute, err_msg|
              - if attribute == :'feedback.service_quality_and_comments'
                li= err_msg
              - else
                li= @user_recent_transaction.errors.full_message(attribute, err_msg)
    
    .row
      .col-xs-12
        = form_for(@user_recent_transaction, url: user_recent_transaction_path, html: {class: 'form-horizontal user_recent_transaction', role: 'form'}) do |f|

          // select country
          = render partial: 'shared/select_country_ctrl', locals: {f: f, resource: @user_recent_transaction, label_class: 'col-sm-5', control_class: 'col-sm-7'}
          
          // date
          .form-group
            = f.label :date, class: 'col-sm-5 control-label'
            .col-sm-3
              .input-group.input-group-fix.date
                = f.text_field :date, value: @user_recent_transaction.date.present? ? @user_recent_transaction.date.strftime('%m/%d/%Y'): '', class: 'form-control mask-date'
                span.input-group-addon
                  i.fa.fa-calendar

          // amount sent
          .form-group
            = f.label :amount_sent, class: 'col-sm-5 control-label'
            .col-sm-3
              .input-group.input-group-fix
                .input-group-addon
                  i.fa.fa-usd.fa-fw
                = money_field f, @user_recent_transaction, :amount_sent, 'form-control mask-money-sent'
          
          // currency
          - if @prefered_currency
            - if @prefered_currency.size > 1
              .form-group
                = f.label :currency, class: 'col-sm-5 control-label'
                .col-sm-3
                  - checked_currency = @user_recent_transaction.currency || (current_user.present? ? current_user.prefered_currency.collect.first : nil)
                  = f.collection_radio_buttons(:currency, @prefered_currency.collect {|currency| [ currency, currency ] }, :first, :last, {prompt: true, checked: checked_currency}) do |b|
                    = b.label( class: "radio-inline", title: b.text )
                      = b.radio_button
                      i *{:class => ['fa fa-fw fa-lg', 'fa-'+b.text.parameterize.downcase]}

            - else
              = f.hidden_field :currency, value: @prefered_currency.first

          - else
            - Country.all.each do |country|
              - if country.receive_currency.size > 1
                .form-group.hidden.receive_currency *{id: "receive_currency_#{country.id}"}
                  = f.label :currency, class: 'col-sm-5 control-label'
                  .col-sm-3
                    = f.collection_radio_buttons(:currency, country.receive_currency.collect {|currency| [ currency, currency ] }, :first, :last, {prompt: true}) do |b|
                      = b.label( class: "radio-inline", title: b.text, for: "user_next_transfer_receive_currency_" + b.text + "_#{country.id}" )
                        = b.radio_button( id: "user_next_transfer_receive_currency_" + b.text + "_#{country.id}" )
                        i *{:class => ['fa fa-fw fa-lg', 'fa-'+b.text.parameterize.downcase]}
          
          // amount received
          .form-group
            = f.label :amount_received, class: 'col-sm-5 control-label'
            .col-sm-3
              .input-group.input-group-fix
                .input-group-addon#amount_receive_currency
                  - if @prefered_currency && @prefered_currency.size == 1
                    i.fa.fa-fw *{:class => ["fa-"+(@user_recent_transaction.currency || @prefered_currency.first).downcase]}
                  - elsif @user_recent_transaction.currency
                    i.fa.fa-fw *{:class => ["fa-"+(@user_recent_transaction.currency).downcase]}
                = money_field f, @user_recent_transaction, :amount_received, 'form-control mask-money-received'

          // originating source of funds
          .form-group
            = f.label :originating_source_of_funds_id, class: 'col-sm-5 control-label'
            .col-sm-7
              = f.collection_radio_buttons(:originating_source_of_funds_id, PaymentMethod.all, :id, :name, {prompt: true, checked: PaymentMethod.first.id}) do |b|
                = b.label( class: "radio-inline", title: b.text )
                  = b.radio_button
                  i *{:class => ['fa fa-fw fa-lg', 'fa-'+b.text.parameterize.downcase]}
          
          // name of service provider
          .form-group
            = f.label :service_provider_id, class: 'col-sm-5 control-label valabel'
            .col-sm-5
              .providers
                = f.collection_radio_buttons(:service_provider_id, @service_providers, :id, :name, {prompt: true, checked: @user_recent_transaction.service_provider.try(:id) || ServiceProvider.first.id}) do |b|
                    = b.label( class: "radio-inline", title: b.text )
                      = b.radio_button
                      =image_tag('provider-icons/'+ b.text.parameterize.downcase + '.png')

                // other provider
                .radio
                  label.radio-inline
                    = radio_button_tag 'user_recent_transaction[service_provider_id]', '', false, "data-toggle" => "modal", "data-target" => "#other_provider_modal"
                    | #{t('.other_provider')}

              .modal.fade#other_provider_modal tabindex="-1" role="dialog" aria-labelledby="other_provider_modal_label" aria-hidden="true"
                .modal-dialog
                  .modal-content
                    .modal-header
                      button.close type="button" data-dismiss="modal"
                        span aria-hidden="true"
                          | &times;
                        span.sr-only
                          | #{t('.close')}
                      h4.modal-title#other_provider_modal_label
                        | #{t('.other_provider_modal_label')}
                    .modal-body
                      = f.fields_for :service_provider_attributes, ServiceProvider.new do |sp|
                        .form-group
                          = sp.label :name, class: 'col-sm-4 control-label'
                          .col-sm-8
                            = sp.text_field :name, class: 'form-control'
                        .form-group
                          = sp.label :money_transfer_page, class: 'col-sm-4 control-label'
                          .col-sm-8
                            = sp.text_field :money_transfer_page, class: 'form-control'
                    .modal-footer
                      button.btn.btn-default type="button" data-dismiss= "modal"
                        | #{t('.close')}
                      a.btn.btn-primary href="javascript:$('#other_provider_modal').modal('hide')"
                        | #{t('.ok')}

          // destination preference for funds
          .form-group
            = f.label :destination_preference_for_funds_id, class: 'col-sm-5 control-label'
            .col-sm-7
              = f.collection_radio_buttons(:destination_preference_for_funds_id, PaymentMethod.for_receiving.all, :id, :name, {prompt: true, checked: PaymentMethod.for_receiving.first.id}) do |b|
                = b.label( class: "radio-inline", title: b.text )
                  = b.radio_button
                  i *{:class => ['fa fa-fw fa-lg', 'fa-'+b.text.parameterize.downcase]}

          // fees for sending
          .form-group
            = f.label :fees_for_sending, class: 'col-sm-5 control-label'
            .col-sm-3
              .input-group.input-group-fix
                .input-group-addon
                  i.fa.fa-usd.fa-fw
                = money_field f, @user_recent_transaction, :fees_for_sending, 'form-control mask-money-fees'

          // send to receive duration
          .form-group
            = f.label :send_to_receive_duration, class: 'col-sm-5 control-label'
            .col-sm-5
              .row
                .col-sm-3
                  = f.text_field :send_to_receive_duration, class: 'form-control mask-minutes input-group-fix', placeholder: '0'
                .col-sm-12
                  = f.collection_radio_buttons(:send_to_receive_duration_interval, User::RecentTransaction.duration_intervals_for_select, :last, :first, {}, {class: ''}) do |b|
                    = b.label( class: "radio-inline", title: b.text )
                      = b.radio_button
                      = b.text

          // provider quality
          = f.fields_for :feedback, @user_recent_transaction.feedback || Feedback.new do |feedback|
            .form-group
              = feedback.label :service_quality, class: 'col-sm-5 control-label'
              .col-sm-7
                .user-rating
                  = feedback.collection_radio_buttons(:service_quality, (1..5).collect{|rate| [rate, rate]}, :first, :last, {prompt: true}) do |b|
                    = b.radio_button( class: "star "+( b.value == 1 ? "required" : ""))

            // comments
            .form-group
              = feedback.label :comments, class: 'col-sm-5 control-label'
              .col-sm-5
                = feedback.text_area :comments, class: 'form-control text-capitalize', cols: '1', rows: '4', maxlength: '512'

          // actions
          .form-group
            .col-sm-5.control-label.f-normal.valabel
              =link_to t('.clear_form'), new_user_recent_transaction_path

            .col-sm-7
              = button_tag type:"submit", class: "btn btn-primary btn-lg" do
                i.fa.fa-fw.fa-check-circle-o
                = t('.submit')